# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Posts"
  url = "#posts"
  weight = 20

[[main]]
  name = "Projects"
  url = "#projects"
  weight = 30

[[main]]
  name = "Experience"
  url = "#experience"
  weight = 40

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 70

[[main]]
  name = "Archive"
  url = "/en/archive/"
  weight = 45
  lang = "en"

[[main]]
  name = "Categories"
  url = "/en/categories/"
  weight = 50
  lang = "en"

[[main]]
  name = "Tags"
  url = "/en/tags/"
  weight = 60
  lang = "en"

[[main]]
  name = "归档"
  url = "/zh/archive/"
  weight = 45
  lang = "zh"

[[main]]
  name = "分类"
  url = "/zh/categories/"
  weight = 50
  lang = "zh"

[[main]]
  name = "标签"
  url = "/zh/tags/"
  weight = 60
  lang = "zh"

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
 [[main]]
   name = "CV"
   url = "/en/files/Ziyang_Lin_CV_2025.pdf"
   weight = 80
